### ISSUE TITLE
Question about `blendmode`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#10]
I was trying to do a report on transparency and ran into a bit of a dilemma with blendmode. This is described in `pst-news08` and I took as an example file [Blend/transparency styles in pstricks and TikZ](https://tex.stackexchange.com/a/183048), but for some reason I can't get the image shown in the forum and I only get an output with four equal images (according to my eyes). I don't know if it's because of my viewer (evince/atril) or I'm not doing things correctly.

```latex
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY ] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
% https://tex.stackexchange.com/a/183048
\documentclass{article}
\usepackage{luapstricks}
\def\Frames{%
\psframe*[linecolor=red](0,1)(3,4)
\psframe[fillcolor=blue,fillstyle=shape](2,2)(5,5)
\psframe[fillcolor=green,fillstyle=shape](1,0)(4,3)
\pscircle[fillcolor=cyan,fillstyle=shape,shapealpha=0.3](1.5,3.5){1.25}}

\begin{document}

\begin{pspicture}(5,5)% default blendmode
\Frames\rput(1.5,3.5){\huge\textbf{0}}
\end{pspicture}
\hfill
\begin{pspicture}(5,5)
\psset{blendmode=1}% type /Compatible
\Frames\rput(1.5,3.5){\huge\textbf{1}}
\end{pspicture}
\begin{pspicture}(5,5)
\psset{blendmode=2}% type /Screen
\Frames\rput(1.5,3.5){\huge\textbf{2}}
\end{pspicture}
\hfill
\begin{pspicture}(5,5)
\psset{blendmode=3}% type /Multiply
\Frames\rput(1.5,3.5){\huge\textbf{3}}
\end{pspicture}

\end{document}
```

![image](https://user-images.githubusercontent.com/2289461/130964549-14ee3c57-33b0-430d-8c05-81cf61dfd4cd.png)

Anyway, this is the output with `luapstricks`

```raw
Extended graphic state modifications dropped since `pdfmanagement-testphase' is
 not loaded../luapstricks.lua:376: Unknown name ".setalphaisshape"
stack traceback:
	[C]: in function 'error'
	./luapstricks.lua:376: in upvalue 'lookup'
	./luapstricks.lua:2388: in upvalue 'execute_tok'
	./luapstricks.lua:2418: in function <./luapstricks.lua:2416>
	(...tail calls...)
	./luapstricks.lua:2418: in upvalue 'execute_ps'
	./luapstricks.lua:2479: in function <./luapstricks.lua:2476>
	[C]: in function 'vf.node'
	./luapstricks.lua:2469: in function <./luapstricks.lua:2460>.
<argument> ...not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...

l.34 \end{document}
                 
? 
```

**Comment by zauguin** [comment]
The `.setalphaisshape` issue is fixed in the current version, the warning

> Extended graphic state modifications dropped since `pdfmanagement-testphase' is
 not loaded.

can be fixed by adding

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
```
at the beginning of the document. (This is required for all the transparency support)

Not sure why, but the support for changing the blendmode is explicitly disabled for modern GhostScript versions at the beginning of `pstricks.pro`. (This also affects `luapstricks` since we emulate such a version)

@hvoss49 Is there a reason why `pstricks.pro` does  `/.setblendmode { pop } def` for revisions greater than 952? On my system `.setblendmode` seems to work correctly with GhostScript 9.54.0. (Corresponding to `revision` 9540)

**Comment by hvoss49** [comment]
GS changed function names _and_ behaviour from 9.27(?) on. `pstricks` tries to catch old and new behaviour. And, of course, it is possible that `/.setblendmode { pop } def` may work again. I have a look at it. Since some years using GS is  kind of pain ...

**Comment by pablgonz** [comment]
The latest update executes the code without errors.
