### ISSUE TITLE
Examples from PSTricks, 7th edition

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#21]
https://hvoss.org/PSTexa/

about 1700 Examples, not all created by now... 
In a first step all set with the `standalone` document class. It is not important that some images are wrong cropped; `standalone` ignores all `\par` commands and uses the `pspicture` coordinates for cropping, if `[pstricks]` is an optional argument. All this will be fixed later. And, of course, there are several wrong output files. However, I am impressed that so many files worked!

Edit: changed doc class to `article`  and using `pdfcrop` 

Edit2: Some images are rubbish, eg. 101, 103, and 110. But this is a problem of the conversion with `pdftoppm`. 
           images with `pst-geo` needs incredible long time to compile ... -> hours!

**Comment by hvoss49** [comment]
New page layout with left (lualatex) and right (latex->drips->ps2pdf) images

**Comment by pablgonz** [comment]
The images look very nice. My eye fails me or I do not see `pst-spinner`, `pst-moire` and `pst-countorplot`?

**Comment by pablgonz** [comment]
@hvoss49  `test1128.tex` work for me.

**Comment by hvoss49** [comment]
Now for me too, moved it back to working one. I am still going through the list ... 

> The images look very nice. My eye fails me or I do not see `pst-spinner`, `pst-moire` and `pst-countorplot`?

That packages were uploaded _after_ the publishing date of the book.

**Comment by pablgonz** [comment]
@hvoss49 `test0414.tex`  and `test0385.tex` works :D

**Comment by pablgonz** [comment]
Can share `test0110`?

**Comment by hvoss49** [comment]
> Can share `test0110`?

The conversion from pdf to png is wrong. I used:

`pdftoppm -f 1 -l 1 -r 75 -png  file.pdf > file.png`

**Comment by pablgonz** [comment]
Has, I see, I get better results using `pdftocairo` when that has happened to me.

**Comment by hvoss49** [comment]
> Has, I see, I get better results using `pdftocairo` when that has happened to me.

what is the command sequence for `pdftocairo` ?

**Comment by pablgonz** [comment]
> what is the command sequence for `pdftocairo` ?

```
pdftocairo -singlefile -r 75 -png file.pdf
```

**Comment by hvoss49** [comment]
I found the problem: without  the optional argument -r 75 everything is fine. I cannot see why the resolution is a problem here. However, with -r 150 it looks good ...

**Comment by pablgonz** [comment]
These are nice examples :)

Question, have you removed the documentation generated with lualatex from your site? (I get 404 from my browser)

**Comment by hvoss49** [comment]
Oh, I was too clever ... ;-)   Did always a rsync for the  contents, but on my side there are no pdf files, so they were deleted. I'll upload
again in a couple of minutes ...
