### ISSUE TITLE
\psRandom

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#24]
```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass[border=5mm]{standalone}
\usepackage{pstricks-add}
\begin{document}
\begin{pspicture}(1,1)
  \psRandom[randomPoints=200,dotsize=8pt, dotangle=45,dotstyle=+]{}
\end{pspicture}
\end{document}

```

Don't know, _what_ is not supported, the rand function?

```
)
(/usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations-basic-d
ictionary-english.trsl) [1...ive/texmf-local/tex/generic/pstricks-lua/luapstric
ks.lua:2342: Not supported
stack traceback:
	[C]: in function 'error'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2342: in function 
<...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2341>
	(...tail calls...)
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2750: in upvalue '
execute_ps'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2811: in function 
<...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2808>
	[C]: in function 'vf.node'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2801: in function 
<...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:2792>.
<argument> ...not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...

```

**Comment by pablgonz** [comment]
@hvoss49 The same thing happens with other macros (`\pstContour`) for example ...try compiling the documentation with this mod `pst-doc.cls` file.

```
\iftutex
  \usepackage{unicode-math}
  \usepackage{libertinus-otf}
  \setmonofont[Scale=MatchLowercase,FakeStretch=0.92]{DejaVu Sans Mono}
  \setmathfont{XITS Math}
\else
  \RequirePackage[T1]{fontenc}
  \RequirePackage{textcomp}
  %\RequirePackage[euler-digits]{eulervm}
  \RequirePackage{bera}
  %\RequirePackage[scaled=0.85]{luximono}
\fi
\usepackage[includeheadfoot,lmargin=2cm,tmargin=1cm,bmargin=1.5cm,rmargin=1.5cm]{geometry}
%\RequirePackage{ifpdf}
```

**Comment by pablgonz** [comment]
@hvoss49 Riding on the momentum, `\psOlympicRings`:

![Captura de pantalla -2021-08-30 14-08-06](https://user-images.githubusercontent.com/2289461/131384655-f98d9225-16df-466d-8ec1-bdbb333dcfdd.png)

**Comment by zauguin** [comment]
> Don't know, _what_ is not supported, the rand function?

`rand` (and `srand`) work, `rrand` doesn't. Basically `rrand` returns a number which can be passed into `srand` to restore the random number generator to the current state. Since `luapstricks` uses Lua's random number generator which doesn't allow to query it's current state (and the state couldn't be expressed in a single integer anyway) `rrand` is not implemented.

Probably we could just implement a custom random number generator instead if this is needed. Do you know why `rrand` is needed anyway? It seems like a rather odd operator to call there.

**Comment by zauguin** [comment]
We now use a random number generator which supports `rrand` and should be compatible with Ghostscript and standard PostScript, so for a fixed `srand` parameter the same random number should get generated now. This generator produces much worse random numbers than the previous one.

**Comment by pablgonz** [comment]
@hvoss49 Have you tried this again ... I tried it with your example and it works.
