### ISSUE TITLE
Question, can anyone test the `pst-vehicle` package?

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#52]
For some reason I seem to have a broken installation of the `pst-vehicle` package, could someone see if this works:

```latex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pst-vehicle}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\begin{document}
\begin{pspicture}(0,0)(4,3)
\def\FuncA{1*cos(x)+1}
\psframe*[linecolor=yellow!10](0,0)(4,3)
\psgrid[style=quadrillage](0,0)(4,3)
\psplot{0}{4}{\FuncA}
\psVehicle[vehicle=\Bike,showSlope]{0.25}{1.2}{\FuncA}
\end{pspicture}
\end{document}
```

**Comment by zauguin** [comment]
`style=quadrillage` doesn't work for me, otherwise the document compiles but the line indicating the slope is wrong.

The slope issue is caused by the use of `x0`: `pst-vehicle` sets a variable named `x0` and calls some code from pst-arrow.tex which sets `x0` to something else.

While I considered most of the other name redefinition issues to be bugs in the external code, this is a bit different. `x0` is not a name with a fixed meaning which you shouldn't be allowed to redefine, so there is nothing really wrong with this usage.

**Comment by pablgonz** [comment]
Thanks, the package is broken at the moment, maybe @hvoss49  has communication with the author (Manuel Luque is listed as a contributor).

**Comment by hvoss49** [comment]
Change x0->X0 in ' pst-vehicle.tex'  and it will work. However, the style qiadrillage is defined in the documentation itself:
```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pst-vehicle}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\begin{document}
\newpsstyle{quadrillage}{subgriddiv=2,gridlabels=5pt,gridwidth=0.3pt,gridcolor=black!50,subgridwidth=0.2pt,subgridcolor=black}

\begin{pspicture}(0,0)(4,3)
\def\FuncA{1*cos(x)+1}
\psframe*[linecolor=yellow!10](0,0)(4,3)
\psgrid[style=quadrillage](0,0)(4,3)
\psplot{0}{4}{\FuncA}
\psVehicle[vehicle=\Bike,showSlope]{0.25}{1.2}{\FuncA}
\end{pspicture}
\end{document}
```

<img width="141" alt="Bildschirmfoto 2021-09-05 um 09 55 49" src="https://user-images.githubusercontent.com/12891199/132119822-24c6a1e9-1119-4ab7-8eab-140b58ec623a.png">

I'll wrote to the maintainer to change the package

**Comment by pablgonz** [comment]
Thanks, then this package can be added to the list of supported packages :D

**Comment by hvoss49** [comment]
No, I am not able to run the complete documentation. Maybe Marcel can give me a hint what's going on here:
```

}] [2]
Overfull \hbox (14.22607pt too wide) in paragraph at lines 193--194
[] 
[3...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:569: Unknown name
 "pdfmark"
stack traceback:
	[C]: in function 'error'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:569: in upvalue 'l
o
```

**Comment by zauguin** [comment]
Have you tried running it after removing the `distiller` option from the document class? Then it no longer throws an error for me, it just takes ages. (Which seems fair since compiling the documentation with `latex` failed with a main memory overflow.)

**Comment by hvoss49** [comment]
Oh, I was blinded by the light ... ;-)

Everything ok now. Will upload the pdf

**Comment by pablgonz** [comment]
The documentation of the rest of the packages from the same author I have been able to compile without major problems

- `pst-geometrictools`
- `pst-perspective`
- `pst-pulley`
- `pst-rputover`
