### ISSUE TITLE
Differences with `\rput`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#53]
The following file gives a different output when using `lualatex`

```latex
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY -dPDFSETTINGS=/prepress -dNOSAFER] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pstricks}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\begin{document}
\rput{34}{%
\psframe(-1,0)(2,1)
\rput[br]{*0}(2,1){\emph{stuff}}}
\end{document}
```

Output `dvips>ps2pdf` (OK)

![Captura de pantalla -2021-09-06 13-39-07](https://user-images.githubusercontent.com/2289461/132245669-cdaa1be3-a52e-4dfc-845a-4d246b600e85.png)

Output `lualatex` (NOT OK)

![Captura de pantalla -2021-09-06 13-39-35](https://user-images.githubusercontent.com/2289461/132245728-03995dea-99ac-4b29-bf6b-84e791c290bf.png)

**Comment by hvoss49** [comment]
Should be fixed ...

**Comment by pablgonz** [comment]
@hvoss49 You uploaded the commit of this fix?

**Comment by hvoss49** [comment]
Hopefully yes, the latest `pstricks.tex`. will also be available tomorrow for all distributions.

**Comment by pablgonz** [comment]
Great, could you upload that version to the repo?

**Comment by hvoss49** [comment]
> Great, could you upload that version to the repo?

It should be already there, the 3.06e, which is the official 3.07 from tomorrow.

**Comment by pablgonz** [comment]
> It should be already there, the 3.06e, which is the official 3.07 from tomorrow.


strange, I can't get the correct output...I'll check.

**Comment by pablgonz** [comment]
@hvoss49 My fault for not updating :( everything is perfect, you can take a look at `pst-eucl`, it compiles without errors, but some drawings are not correct.

**Comment by hvoss49** [comment]
> @hvoss49 My fault for not updating :( everything is perfect, you can take a look at `pst-eucl`, it compiles without errors, but some drawings are not correct.

You mean page 97??  I have it fixed here but upload tomorrow ...

**Comment by pablgonz** [comment]
> You mean page 97?? I have it fixed here but upload tomorrow ...

Yes, 7. Helper Macros and A.2. Transformation de polygones et courbes together with the following

**Comment by hvoss49** [comment]
fixed and upload to https://hvoss.org/PSTexa/pst-eucl-doc.pdf

**Comment by pablgonz** [comment]
Nice :D

**Comment by pablgonz** [comment]
@hvoss49 You can take a look at 
https://luapstricks.typesetting.eu/version/action-docs/doc/pst-eucl-doc.pdf
from page 93?

**Comment by hvoss49** [comment]
I suppose that it is fixed in my own version, will have a look ...

**Comment by zauguin** [comment]
@pablgonz I regenerated the docs after @hvoss49's update, it looks god now.

**Comment by pablgonz** [comment]
@zauguin @hvoss49 Yes, now it's perfect, just one doubt, when executing:

```
$ pdffonts pst-eucl-doc.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
JAIXAE+DejaVuSansMono-Bold           CID TrueType      Identity-H       yes yes yes     10  0
VJPMOK+LibertinusSans-Bold           CID Type 0C       Identity-H       yes yes yes     11  0
LAPYOB+LibertinusSerif-Regular       CID Type 0C       Identity-H       yes yes yes     12  0
BCPHEO+DejaVuSansMono                CID TrueType      Identity-H       yes yes yes     13  0
YCFDSN+LibertinusSans-Regular        CID Type 0C       Identity-H       yes yes yes     64  0
HXJSTX+LibertinusMath-Regular        CID Type 0C       Identity-H       yes yes yes    187  0
UHAGGG+LibertinusMath-Regular        CID Type 0C       Identity-H       yes yes yes    188  0
NNTECO+PSTricksDotFont               CID Type 0C       Identity-H       yes yes yes    189  0
VCTKYK+LibertinusSerif-Italic        CID Type 0C       Identity-H       yes yes yes    197  0
BEIWOW+TeXGyreHeros-Regular          CID Type 0C       Identity-H       yes yes yes    199  0
TDPWLF+LibertinusMath-Regular        CID Type 0C       Identity-H       yes yes yes    271  0
RDKAUI+LibertinusSerif-Bold          CID Type 0C       Identity-H       yes yes yes    650  0
AQNGYK+LibertinusSerif-Regular       CID Type 0C       Identity-H       yes yes yes    968  0
LXSQOK+TeXGyrePagella-Regular        CID Type 0C       Identity-H       yes yes yes   2737  0
EWUXJA+StandardSymL                  Type 1            Builtin          yes yes no    2738  0
PLELFS+TeXGyreTermes-Regular         CID Type 0C       Identity-H       yes yes yes   2739  0
VMBCIK+DejaVuSansMono-Oblique        CID TrueType      Identity-H       yes yes yes   3328  0
```
I am intrigued by the `StandardSymL` font on page 80...why is it there?

**Comment by hvoss49** [comment]
that is hardcoded in pst-eucl:
```
      /s1 { /StandardSymL findfont \psk@fontscale\space scalefont setfont } bind def
```

**Comment by pablgonz** [comment]
@hvoss49 Thanks, maybe I'm a bit confused, that font (`StandardSymL`) is only used for the degree symbol (on that specific page), the rest of the font `PSfont=Palatino-Roman` is mapped by `luapstricks`, am I right?

But according to:

https://github.com/zauguin/luapstricks/blob/41df2830d7b0c0a069ec55b0ec16cbe62dfce1dd/luapstricks.lua#L363

should appear `StandardSymbolsPS` (not `StandardSymL`) when executing `$ pdffonts pst-eucl-doc.pdf`.

**Comment by hvoss49** [comment]
that's so long ago so I cannot remember why it is there. I'll have a closer look tomorrow ...

**Comment by zauguin** [comment]
> But according to:
> 
> https://github.com/zauguin/luapstricks/blob/41df2830d7b0c0a069ec55b0ec16cbe62dfce1dd/luapstricks.lua#L363
> 
> 
> should appear `StandardSymbolsPS` (not `StandardSymL`) when executing `$ pdffonts pst-eucl-doc.pdf`.

There is an additional remap

https://github.com/zauguin/luapstricks/blob/41df2830d7b0c0a069ec55b0ec16cbe62dfce1dd/luapstricks.lua#L326

so the font used is actually `usyr` which identifies itself as `StandardSymL` (as can be seen in `usyr.pfb` in the line `/FontName /StandardSymL def`) since it's almost exclusively used as an replacement for that font instead of as an independent font.

More generally the name shown in `pdffonts` is a property of the font which is not intrinsically connected with the name actually used for loading it.
