### ISSUE TITLE
Documentation of `pstricks` (base) and regression tests

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#55]
At the moment, `luapstricks` support testing is based on testing support for various packages (visual inspection) along with some regression testing.

It would be great to be able to compile the `pst-user` documentation chapters referring to `pstricks` (base).

I tried but failed miserably, in my mind I think from there you could create some regression tests for the basic elements (\rput for example) and then place the elements that have been added during the time described in `pst-news`.

**Comment by hvoss49** [comment]
`pst-user` is more than 20 years old and has a _lot of_ special definitions for the documentclass. It is much more easier to extract the examples and create a new document.

**Comment by pablgonz** [comment]
It is true :(
I have tested (I think) all the examples that are proposed in `pst-user` (base) and they work OK, of course I cannot be 100% sure (I may miss some) together with those described in pst-news since 2008 and so far so good.

**Comment by pablgonz** [comment]
Closed in favor of  #58
