### ISSUE TITLE
pst-bezier and << ...>> operator

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#57]
This package uses the to luapstricks unknown operators. Can it be fixed?

The special character sequences << and >> (LanguageLevel 2) are self-delimiting tokens that denote the construction of a dictionary, much the same as [ and ] de- note the construction of an array. They are intended to be used as follows:
<< key1 value1 key2 value2 ... keyn valuen >>

```
warning  (file /usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex
.map) (map file): ambiguous entry for 'uzdr': font file present but not include
d, will be treated as font file not present
}...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:569: Unknown name 
">>"
stack traceback:
	[C]: in function 'error'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:569: in upvalue 'l
ookup'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:3031: in upvalue '
execute_tok'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:3061: in upvalue '
```

**Comment by zauguin** [comment]
I find it kind of fascinating that we have `<<`, but not `>>`. (It makes since implementation wise, but it still seems odd)

Anyway, I added it.

**Comment by hvoss49** [comment]
> I find it kind of fascinating that we have `<<`, but not `>>`. (It makes since implementation wise, but it still seems odd)
> 
> Anyway, I added it.

works!
