### ISSUE TITLE
pst-user and missing defaultmatrix

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#58]
I try to compile the pst-user and get

```
Extended graphic state modifications dropped since `pdfmanagement-testphase' is
 not loaded.] [106] (./pst-user.tmp) [107...ive/texmf-local/tex/generic/pstrick
s-lua/luapstricks.lua:569: Unknown name "defaultmatrix"
stack traceback:
	[C]: in function 'error'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:569: in upvalue 'l
o
```

**Comment by zauguin** [comment]
I just pushed a implementation, but I didn't test it yet.

**Comment by hvoss49** [comment]
I'll test it. The current pst-user was created without hyperref and the overlay stuff, which needs the defaultmatrix

**Comment by hvoss49** [comment]
> I just pushed a implementation, but I didn't test it yet.

I suppose "just" is not really "just" ... :-)

**Comment by zauguin** [comment]
> I suppose "just" is not really "just" ... :-)

More like "pushed" actually being "tried to push and ignored the error message"... Now it should be there.

**Comment by pablgonz** [comment]
@hvoss49 I think `pst-oval` can be added to the list now :D
