### ISSUE TITLE
Compiling with LuaLaTex a psttricks project without any effect

### ISSUE THREAD

**Issue by teo-chelmus** [zauguin/luapstricks#59]
Hello.
I post a question on tex.stackexchange.com at the link below:
[https://tex.stackexchange.com/questions/614556/pstricks-compiled-with-xelatex-with-many-errors-but-return-a-pdf-file#614556](url)

But the preliminary answer did not work for me. I followed the steps on this page and after compiling with LuaLaTex (using WinEdit) it returned to me more errors than compiling with XeLaTeX. In addition, now pictures were generated after compiling with LuaLaTex.

Compiling with XeLaTex, the compiler produced the expected result but with many compilation errors. What is the problem? How can one fix it?

Is it enough to copy the luapstricks.lua file to the directory where my .tex file is located? Do I need to call the .lua file from the .tex file using a specific instruction? Thank you!
P.S. I attached the log file.
[seq.log](https://github.com/zauguin/luapstricks/files/7126498/seq.log)

**Comment by hvoss49** [comment]
works fine here with:

```
\documentclass[a4paper]{article}

\usepackage{graphicx} 
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{pstricks}
\usepackage{pst-plot}

\begin{document}

\psset{yunit=.5cm,xunit=0.4cm}
\begin{pspicture}(-1,-0.2)(22,7)
   \psaxes[labels=none,ticks=none]{->}(0,0)(20.5,6.5)
   \def\f{3 3 0.8 neg x exp mul add}
   \psframe[fillstyle=solid,fillcolor=yellow,linecolor=yellow](8,2.5)(20.5,3.5)
   \rput(21,0){$n$}
   \rput(0,6.8){$a_n$}
   \psplot[plotpoints=21,linecolor=blue,linestyle=none,showpoints=true]{0}{20}{\f}
   \psline[linestyle=dashed](8,0)(8,6)
   \rput(14,70){\red$n\geq N$}
   \psline[linestyle=dashed](0,85)(16,85)
   \psline[linestyle=dashed](0.05,2.5)(20.5,2.5)
   \psline[linestyle=dashed](0.05,3.5)(20.5,3.5)
   \psline[linecolor=blue](0,3)(20.5,3)
   \uput[l](0,3){\blue$\ell$}
   \rput(17,4.5){$\lim\limits_{n\to+\infty}a_n =\ell$}
\end{pspicture}

\vspace{5cm}

\begin{pspicture}(-0.5,-0.2)(13,3.5)
   \psset{xunit=0.5cm, yunit=.025cm}
   \psaxes[labels=none,ticks=none]{->}(0,0)(16,130)
   \def\f{.5 x mul x mul x add 1 add }
   \psframe[fillstyle=solid,fillcolor=yellow=red,linecolor=yellow](12,130)(16,85)
   \rput(16.3,0){$n$}
   \rput(0,135){$a_n$}
   \psplot[plotpoints=17,linecolor=blue,linestyle=none,showpoints=true]{0}{15}{\f}
   \psline[linestyle=dashed](12,0)(12,130)
   \psline[linestyle=dashed](0,85)(16,85)
   \rput(9,105){$\lim\limits_{n\to+\infty}a_n =+\infty$}
\end{pspicture}

\end{document}
```

<img width="246" alt="Bildschirmfoto 2021-09-08 um 08 52 06" src="https://user-images.githubusercontent.com/12891199/132460732-37ee745d-72ec-4576-a3bb-3fdfc846524b.png">

**Comment by teo-chelmus** [comment]
I also used the Overleaf platform (avoiding possible problems with my hardware or Miktex). Compiling with XeLaTex, it works fine, no errors, but compiling with LuaLaTex does not generate any pictures and returned some errors (see the picture below). 

Where can the problem be? Why it does not work the compilation on my local PC, even with XeLaTeX? What can the source of errors be? (in both cases).

**Comment by hvoss49** [comment]
You need the file `luapstricks.lua` installed, which is _not_ part of any TeX distribution and _not_ part of overleaf!

**Comment by pablgonz** [comment]
At the moment I don't think this is possible in overleaf. If you follow the README instructions with a local TeX installation it will work for sure.
