### ISSUE TITLE
Gouraud shading and unknown name shfill

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#62]
I am trying to get the `\psGTriangle` working, but we need the shfill operator. Can it be implemented?

```
(/usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations-basic-d
ictionary-english.trsl) [1...ive/texmf-local/tex/generic/pstricks-lua/luapstric
ks.lua:597: Unknown name "shfill"
stack traceback:
	[C]: in function 'error'

```

**Comment by hvoss49** [comment]
With this problem fixed we are nearly at the end of "the whole story". Only the char path stuff is then left.

**Comment by zauguin** [comment]
> I am trying to get the `\psGTriangle` working, but we need the shfill operator. Can it be implemented?

I added an initial version. (It doesn't support all uses of `shfill` at the moment, but Shading mode 4 (free-form Gouraud shading) should work.

**Comment by hvoss49** [comment]
thanks! Works fine!

**Comment by hvoss49** [comment]
```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass{standalone}
\usepackage{pstricks-add}
\begin{document}

\begin{pspicture}
\psGTriangle*(0,0)(9,10)(10,3){black}{white!50}{red!50!green!95}
\end{pspicture}

\end{document}

```
<img width="326" alt="Bildschirmfoto 2021-09-10 um 13 56 54" src="https://user-images.githubusercontent.com/12891199/132849951-15218c57-0a41-460c-9777-7a2b03a727d7.png">

**Comment by pablgonz** [comment]
@hvoss49  Can check https://github.com/zauguin/luapstricks/issues/25 and close?
