### ISSUE TITLE
pst-dart and shifted object

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#64]
If I run the example with the article class, the boars is shifted, running it with the `standalone` class all is fine:
```

\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
%\documentclass[border=5mm]{standalone}
\documentclass{article}
\usepackage{pst-dart}
\begin{document}

\begin{pspicture}(-2,-3)(6,4)
\psDartBoard[preCode={[1 0.2 0.5 1 0 0 ] concat},fontsize=18pt,unit=1.5] 
\psDart[unit=0.5,rot=110](1,-1)
\end{pspicture}

\end{document}
```

Must be a problem with the current matrix and concat.

output with article:

<img width="386" alt="Bildschirmfoto 2021-09-11 um 11 31 14" src="https://user-images.githubusercontent.com/12891199/132943444-de207d04-c98b-4942-89de-416ee4a1e819.png">

Output with standalone:

<img width="357" alt="Bildschirmfoto 2021-09-11 um 11 31 44" src="https://user-images.githubusercontent.com/12891199/132943457-bacfbda6-f10a-4d98-bc8c-8a7a54010ce8.png">

**Comment by hvoss49** [comment]
I have another solution, we can forget this issue ...

**Comment by zauguin** [comment]
It sounded like something which should be fixed though. Do you know what exactly caused this?

**Comment by hvoss49** [comment]
From my point of view it is a problem with the transformation matrix. I suppose that the use of \pstVerb in this case is not a good idea. But I am not sure.

**Comment by zauguin** [comment]
I agree, the use of `\pstVerb` here means that the transformation is centered on the lower left corner of the page, so the position on the page changes the location of the graphics. The same issue happens with `latex->dvips->gs`, just less extreme since there the coordinate system is based on the upper corner which is nearer.

Compensating for this with
```
\psDartBoard[preCode={currentpoint 2 copy translate [1 0.2 0.5 1 0 0 ] concat neg exch neg exch translate},fontsize=18pt,unit=1.5]
```
confirms that the issue disappears.

**Comment by hvoss49** [comment]
I changed it to a more user friendly  option `bordviewpoint=x y z`
