### ISSUE TITLE
`variableLW` in `pstricks` (base)

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#65]
I was testing the macros added to `pstricks` (base) and came across the following (adapted from `pst-news10`):

```latex
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY -dPDFSETTINGS=/prepress -dNOSAFER] }
% arara: clean: { extensions : [ aux, log, dvi ] }
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pstricks-add}
\setlength{\parindent}{0pt}
\addtolength{\hoffset}{-1.5cm}
\pagestyle{empty}
\begin{document}
% from pst-news10
\psset{endLW=15pt}
 \begin{pspicture}(-3.5,-2.5)(3.5,2.5)
 \psellipse[linejoin=2,variableLW,startLW=1pt,linecolor=green!40](0,0)(3,1)
\end{pspicture}
\quad 
\psset{endLW=15pt}
\begin{pspicture}(-2.5,-2.5)(2.5,2.5)
\pscircle[variableLW,startLW=1pt,linecolor=blue!40]{2}
\end{pspicture}
\quad
\psset{endLW=15pt}
\begin{pspicture}(-2.5,-2.5)(2.5,2.5)
\psarc[variableLW,startLW=1pt,linecolor=red!40](0,0){2}{10}{300}
\end{pspicture}
\quad
\psset{endLW=15pt}
\begin{pspicture}(-3.5,-2.5)(3.5,2.5)
\psellipticarc[variableLW,startLW=1pt,linecolor=black!40](0,0)(3,1){90}{30}
\end{pspicture}
\quad
\begin{pspicture}(-2.5,-2.5)(2.5,2.5)
\pscurve[variableLW,startLW=1pt,endLW=20pt,variableColor](-1,0.5)(-2,1)(2,2)(-1,-2)(2,-2)
\end{pspicture}
\quad
\begin{pspicture}(-2.5,-2.5)(2.5,2.5)
\pscurve[variableLW,startLW=1pt,endLW=20pt](-1,0.5)(-2,1)(2,2)(-1,-2)(2,-2)
\end{pspicture}
\quad
\begin{pspicture}(-5,-3)(5,3)
\psplot[variableLW,startLW=1pt,endLW=20pt,linecolor=magenta!60,variableColor,algebraic,plotpoints=3000,startWL=500,endWL=700]{-5}{5}{2*sin(2*x)+cos(x)}
\end{pspicture}
\quad
\psset{endLW=24pt}
\begin{pspicture}(-5,-5)(5,5)
\psparametricplot[variableLW,startLW=1pt,endLW=60pt,linecolor=red,variableColor,algebraic,plotpoints=3000,plotstyle=curve,opacity=0.4,strokeopacity=0.4,endWL=600]{-5}{5}{t*sin(t) | t*cos(t)}
\end{pspicture}
\end{document}
```

The output with `dvips>ps2pdf` is as follows:

![test-crop-1](https://user-images.githubusercontent.com/2289461/133171733-0391a64f-680d-46e3-b0fc-6e5eb93f22e2.png)
![test-crop-2](https://user-images.githubusercontent.com/2289461/133171736-e8517172-7fa0-4f93-84e8-32d7647a682f.png)

But the output is tricky to say the least (it is taken with `pdftocairo -png`). When looking at the pdf file directly, you can see something else:

Google Chrome for example:

![Captura de pantalla 2021-09-13 104332](https://user-images.githubusercontent.com/2289461/133172224-2fbe094c-2ffe-48d3-96de-6622cd1fdfeb.png)

In addition, the output using `lualatex` is very different:

![test-crop-1](https://user-images.githubusercontent.com/2289461/133172568-386abad2-531d-4db9-9bd4-14506eab0d5b.png)
![test-crop-2](https://user-images.githubusercontent.com/2289461/133172570-560a14fc-99c9-4f77-9fd5-14969098e827.png)

And pdf looks very ugly, Google Chrome for example:

![Captura de pantalla 2021-09-13 104332](https://user-images.githubusercontent.com/2289461/133172763-a595417d-3536-4827-a9d2-78791d1b35c4.png)

The firefox viewer shows the curves more rounded and in Acrobat DC it looks a bit better, but the output is wrong (apologies, I only have win10 at the moment).

**Comment by pablgonz** [comment]
In linux I get the same, with `lualatex` the output is wrong, and with `dvips/ps2pdf` it looks good with some viewers and not with others, with evince it looks good but the small pages (on the right) are wrong :(

**Comment by zauguin** [comment]
It should work better with the new version which uses some additional decimal digits in the PDF output.

**Comment by zauguin** [comment]
> with evince it looks good but the small pages (on the right) are wrong :(

On my system the output with evince actually depends on the Zoom level, only after zooming in it looks acceptable.

**Comment by pablgonz** [comment]
@zauguin I have tried with the last code you uploaded and it does not work with any linux viewer :(

**Comment by zauguin** [comment]
> I have tried with the last code you uploaded and it does not work with any linux viewer :(

Have you tried opening it in Firefox? That seems to give the best results for me.

**Comment by pablgonz** [comment]
Apologies for the delay, we are on national holiday :D

> 
> Have you tried opening it in Firefox? That seems to give the best results for me.

Yes and no, the first two images are not correct, of course the firefox output is the best, so I'm left wondering about the implementation behind this in `pstricks`, I haven't read (as far as I've searched) that the generated pdf is dependent on any viewer feature. Coming back to this, this is the dvips output as seen from firefox (180%)

![Captura de pantalla -2021-09-19 20-26-51](https://user-images.githubusercontent.com/2289461/133946280-d9ecc0ec-9849-4558-aa4d-fae4038ac5ea.png)

this is the lualatex output as seen from firefox (180%)

![Captura de pantalla -2021-09-19 20-27-49](https://user-images.githubusercontent.com/2289461/133946304-96d7af52-fe6f-4c40-8e61-d1d7d07bc654.png)

This mystery has me more than intrigued :D

**Comment by zauguin** [comment]
> I haven't read (as far as I've searched) that the generated pdf is dependent on any viewer feature.

As far as I can tell, these are just rounding artifacts. These PDF files are *huge* with a lot of tiny segments drawn individually. So the drawing code has to deal with the case that it has to draw many objects whose coordinates are almost the same, which can trigger numerical instabilities. This seems to be confirmed by the issues getting a bit better after adding more decimal digits. Since this kind of stuff will depend on many details of how the PDF file gets drawn and the exact commands used to invoke them, it's rather unsurprising that different viewers show different results and that GhostScript and luapstricks (which generate very different PDF files) show different output.

I'm convinced though that (except for the line from the middle) this is not caused by incorrect PDF files and instead just rendering artifacts.

**Comment by pablgonz** [comment]
Oh, I get it, that's why the same thing happens when using XeTeX so it must be what you say.

**Comment by hvoss49** [comment]
You can play with the optional argument setflat which is preset to 0.1. It defines the smallest distance between two line segments. There is no other chance to reduce the file size if you want a variable line width or variable color. I rewrote that macro but it is still slow with lualatex. I have to plot the curve twice: the first time for the length of it to calculate the dWidth and dColor. The second run for the curve itself.
