### ISSUE TITLE
unknown Resolution

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#69]
I have no idea, why Reaolution is unknown to luapstricks.

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass[12pt,a4paper]{article} 
\usepackage{fontspec}
\usepackage{pstricks} 
\usepackage{pst-grad} 
\usepackage{pst-light3d}
%
\begin{document}

\DeclareFixedFont{\Bf}{T1}{ptm}{b}{n}{3cm} 
\psset{linestyle=none,fillstyle=solid,fillcolor=magenta,}% 
\PstLightThreeDText[LightThreeDXLength=0.5, LightThreeDYLength=-1]{\Bf Test}\\[1cm]
\PstLightThreeDText[LightThreeDXLength=-1, LightThreeDYLength=0.5]{\Bf Test}

\end{document}
```
The error:

```dist/tex/latex/luapstricks/luapstricks.lua:3758: ...texlive/texmf-dist/tex/late
x/luapstricks/luapstricks.lua:736: Unknown name "Resolution"
stack traceback:
	[C]: in function 'error'
	...texlive/texmf-dist/tex/latex/luapstricks/luapstricks.lua:3842: in function 
<...texlive/texmf-dist/tex/latex/luapstricks/luapstricks.lua:3822>
	[C]: in function 'vf.node'

```

**Comment by zauguin** [comment]
> why Reaolution is unknown to luapstricks

The "why" part is relatively easy to answer: `Resolution` is defined in `@start` which itself defined in `tex.pro` and automatically invoked by `dvips`. On the other hand `tex.pro` is never loaded by luapstricks and luapstricks also doesn't run `@start`, so it never defines `Resolution`.

The other question is: If we define this, what should be the value? 720 to reflect the initial matrix? The value of `\pdfimageresolution`? `\pdfpkresolution`? Something else?

**Comment by hvoss49** [comment]
Good question .... 
For the above example it is defined both to 600 , /VResolution and /Resolution.

**Comment by hvoss49** [comment]
and by the way: pst-light3d uses `reversepath`

**Comment by zauguin** [comment]
I added Resolution and VResolution in TeXDict (not as numbers but as operators querying the current `\pdfpkresolution`). By default this is 600, but can be different if the document changes it.

Technically this means that the example document can be compiled now. (It doesn't actually give the expected output though since it relies on redefining `show` which doesn't have a big effect in LuaLaTeX. This also hides the issue of `reversepath` and `charpath` not being defined)

**Comment by zauguin** [comment]
> and by the way: pst-light3d uses `reversepath`

Do you have an example document for `reversepath` which does not depend on `charpath`?

**Comment by hvoss49** [comment]
```
\documentclass[border=12pt]{standalone}
\usepackage{pstricks}
\def\CW{\psline(2,2)(3,4)(4,1)(4,-3)}
\begin{document}    
    \begin{pspicture}[showgrid=top](-5,-5)(5,5)
    \pscustom[fillstyle=solid,fillcolor=red,linewidth=5pt]
    {
        \CW % (2,2)(3,4)(4,1)(4,-3)
        \reversepath % now (4,-3)(4,1)(3,4)(2,2)
        \scale{-1 1}
        \CW % (-2,2)(-3,4)(-4,1)(-4,-3)
        \closepath % line from -4,-3 to 4,-3 counter clockwise path
        \pscircle(0,0){1}% clockwise: circle not filled (scale -1 1)!!
    }% The inner of the circle is _not_ inside the path
    \end{pspicture}
\end{document}
```

**Comment by zauguin** [comment]
I added `reversepath`.

**Comment by hvoss49** [comment]
> I added Resolution and VResolution in TeXDict (not as numbers but as operators querying the current `\pdfpkresolution`). By default this is 600, but can be different if the document changes it.

Must I used the dict TeXDict?  This still fails:

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article} 
\usepackage{pst-light3d}
\begin{document}
\DeclareFixedFont{\Bf}{T1}{ptm}{b}{n}{3cm} 
\PstLightThreeDText[fillstyle=solid,fillcolor=white]{\Bf Test}

%\def\PstLightThreeDText@i{%        from pst-light.tex
%  \pst@makebox{%
%    \PstLightThreeD@i{%
%      /LightThreeDDXa LightThreeDDX Resolution 100 div mul def
%      /LightThreeDDYa LightThreeDDY VResolution 100 div mul def

\end{document}
```

**Comment by zauguin** [comment]
While it's in `TeXDict`, `luapstricks` automatically does the equivalent of `TeXDict begin` so the should be no extra action required.

Also the code you send compiles on my system.

**Comment by hvoss49** [comment]
Ok. I got it:

```
) (/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/t1ptm.fd) [1...ve/2021/texmf-dist/tex/latex/luapstricks/luapstricks.lua:3758: ...ve/2021/texmf-dist/tex/latex/luapstricks/luapstricks.lua:736: Un
known name "Resolution"
```

the official `luapstricks.lua` is from my point of view in the wrong directory! kpsewhich first find a `luapstricks` in the `latex` directory and uses this one instead of my own in  the `generic` directory.

However, `luapstricks.lua` should be in  `/texmf-dist/tex/lualatex/luapstricks/`.   or `.../luatex/...` if it also works for `luatex`.
