### ISSUE TITLE
Update support for `liftpen`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#7]
At the moment the `liftpen` option is supported by `luapstricks` (compiles without errors), but the result is not as expected.

```
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY ] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
\documentclass{article}
\usepackage{luapstricks}
\pagestyle{empty}
\begin{document}
% liftpen=0
\begin{pspicture}[showgrid](4,3)
  \pscustom[linewidth=2pt,fillstyle=solid,fillcolor=gray]{%
    \pscurve(0,2)(1,2.5)(2,1.5)(4,3)
    \pscurve(4,1)(3,0.5)(2,1)(1,0)(0,.5)}
\end{pspicture}\hspace*{1em}
% liftpen=1
\begin{pspicture}[showgrid](4,3)
  \pscustom[linewidth=2pt,fillstyle=solid,fillcolor=gray]{%
    \pscurve(0,2)(1,2.5)(2,1.5)(4,3)
    \pscurve[liftpen=1](4,1)(3,0.5)(2,1)(1,0)(0,.5)}
\end{pspicture}\hspace*{1em}
% liftpen=2
\begin{pspicture}[showgrid](4,3)
  \pscustom[linewidth=2pt,fillstyle=solid,fillcolor=gray]{%
    \pscurve(0,2)(1,2.5)(2,1.5)(4,3)
    \pscurve[liftpen=2](4,1)(3,0.5)(2,1)(1,0)(0,.5)}
\end{pspicture}
\end{document}
```

Expected output

![image](https://user-images.githubusercontent.com/2289461/130858460-03274f99-4a31-4b96-ad2f-7ac7d733d9e5.png)

Current output

![image](https://user-images.githubusercontent.com/2289461/130858572-f5fbb540-7f0f-47f8-97c1-5c62cf9de0be.png)

**Comment by zauguin** [comment]
Should be fixed now, even though similar issues might still come up. This was caused by some differences in error handling and the current fix only solves the very direct issues and not the general system which behaves a bit different than it probably should.

**Comment by pablgonz** [comment]
Thank you, with this I can complete the previous report :D
