### ISSUE TITLE
dotstyle=o

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#70]
`dotstyle=o` was a white filled circle, but is now the same as a circle. 

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pstricks}
\begin{document}
\begin{pspicture}[showgrid=true](1,-1)(4,1)
\pscurve[showpoints=true,dotstyle=o](2.1,-0.2)(2.5,0.2)(3.2,0.235)(3.8,-0.2)
\end{pspicture}
\begin{pspicture}[showgrid=true](1,-1)(4,1)
\pscurve[showpoints=true,dotstyle=Circle](2.1,-0.2)(2.5,0.2)(3.2,0.235)(3.8,-0.2)
\end{pspicture}
\end{document}
```

**Comment by zauguin** [comment]
I currently get `Unknown name "Points"` when trying that file (and `Error: /undefined in Points` when trying latex>dvips>ps2pdf). (Might be a local issue though) So local testing is currently a bit hard for me.

Anyway, `pstricks-dots.tex` for some reason uses `\newpsfontdot` instead of `\newpsfontdotH` to define `{o}` and therefore no longer defines a filling. I would assume that replacing

```
\newpsfontdot{o}[1.5 0.0 0.0 1.5 0 0]{PSTricksDotFont}{<63>}
```
with
```
\newpsfontdotH{o}[1.5 0.0 0.0 1.5 0 0]{PSTricksDotFont}{(c)}{(b)} % or {<63>}{<62>}
```
restores the old behavior. There are quite some other entries with similar changes though.

BTW, where is the factor `1.5` coming from? Is there a scaling issue with the font?

**Comment by hvoss49** [comment]
I introduced a bug in `pstricks.pro`.  Delete the use of a userdict for

```
/OpenCurve { 
%  5 dict begin
  NArray n 3 lt 
    { n { pop pop } repeat } 
    { BOC /n n 3 sub def n { NC } repeat EOC } ifelse 
%  end
} def
```

An updated version is already on CTAN. 

The factor 1.5 is there since I am using PSTricks and I do not know why Timothy used it 30 years ago ... 
I forgot the H in the definitions ...

**Comment by hvoss49** [comment]
If I am right, then you do not uploaded the OpenType variant of the dot font to CTAN?  If yes,  should I save it as part of PSTricks or do you want to put it into the luapstricks?  Both are ok for me ...

**Comment by hvoss49** [comment]
> BTW, where is the factor `1.5` coming from? Is there a scaling issue with the font?

I compared old documents with new ones and 1.5 is indeed too large. I'll change it.

**Comment by zauguin** [comment]
> If I am right, then you do not uploaded the OpenType variant of the dot font to CTAN? If yes, should I save it as part of PSTricks or do you want to put it into the luapstricks? Both are ok for me ...

I just added it to the luapstricks list, so I'll add it there with the next release.

**Comment by hvoss49** [comment]
> > If I am right, then you do not uploaded the OpenType variant of the dot font to CTAN? If yes, should I save it as part of PSTricks or do you want to put it into the luapstricks? Both are ok for me ...
> 
> I just added it to the luapstricks list, so I'll add it there with the next release.

Ping ... :-)

**Comment by zauguin** [comment]
> Ping ... :-)

Pong :)

It is [on CTAN](https://www.ctan.org/tex-archive/graphics/pstricks/contrib/luapstricks) and [in TeX Live](http://tug.org/svn/texlive?view=revision&revision=60659) since yesterday.
