### ISSUE TITLE
Difference in show origin (axes) `pst-cie`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#72]
Hi, I don't know if this is directly directly related, but, I leave it here:

```latex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pst-cie}
\begin{document}
\begin{pspicture}(-1,-1)(15,15)
  \psChromaticityDiagram[unit=1.5,contrast=0.5]%
  \pstPlanck[unit=1.5]
\end{pspicture}
\end{document}
```

When using `dvips`:

![image](https://user-images.githubusercontent.com/2289461/140405888-e3c569ae-1f17-4ee4-b33b-73f37081a31a.png)

When using `lualatex`:

![image](https://user-images.githubusercontent.com/2289461/140406046-9006e019-336c-4b30-8c9e-66b21869e000.png)

There is a difference in how the orignen values are displayed.

**Comment by hvoss49** [comment]
I fixed it in `pst-cie.pro`

**Comment by pablgonz** [comment]
@hvoss49 To fast :D

**Comment by hvoss49** [comment]
and uploaded to CTAN ...

**Comment by pablgonz** [comment]
Thanks
