### ISSUE TITLE
Bug with color in ps mode

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#78]
```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass{article}
\usepackage{pstricks,multido}
\begin{document}

Does not work:

\multido{\iC=0+1}{11}{%
  \definecolor[ps]{rainbow}{hsb}{0.9 \iC\space 15 div sub 1 \iC\space 11 div sub 0.7 }%
  \psline[linewidth=5pt,linecolor=rainbow](3,3)%}
}    
 
Works:

\multido{\iC=0+1}{11}{%
  \definecolor[ps]{rainbow}{hsb}{0.5  0.2  0.7 }%
  \psline[linewidth=5pt,linecolor=rainbow](3,3)%}
}
\end{document}

```

Output with up-to-date TL and  latest `luapstricks.lua` (github)

[[Loading MPS to PDF converter (version 2006.09.02).]
)...2021/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4145: attempt to concatenate a nil value (local 'result')
stack traceback:
	...2021/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4145: in function <...2021/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4142>.
\c@lor@to@ps #1\@@ ->\luaPSTcolor {#1}
                                      
l.12 }
    
?](url)

**Comment by zauguin** [comment]
You're "works" block didn't work for me either. In any case, it should be fixed with the latest commit.

**Comment by hvoss49** [comment]
thanks!
