### ISSUE TITLE
Problem between pstricks, xcolor, luatex and pdfmanagement

### ISSUE THREAD

**Issue by fpantigny** [zauguin/luapstricks#88]
With recent version of `pstricks` (2023/10/05 v0.73), I have an error with the following code:

```
\documentclass{article}
\usepackage{xcolor}
\usepackage{pstricks}

\begin{document}

Some text.

\begin{pspicture}(0,0)(5,5)
\psline(0,0)(1,1)
\end{pspicture}

\end{document}
```

The message error is the following :

`! LaTeX hooks Error: Sorting rule for 'package/xcolor/after' hook applied too late`

When `pstricks` is loaded before `xcolor`, there is no error.

**Comment by hvoss49** [comment]
Do not load `xcolor`, it is already be done by PSTricks itself.

**Comment by fpantigny** [comment]
Yes. But if xcolor is previously loaded by the document class that I use?

 

De : Herbert Voß ***@***.***> 
Envoyé : lundi 6 novembre 2023 20:20
À : zauguin/luapstricks ***@***.***>
Cc : fpantigny ***@***.***>; Author ***@***.***>
Objet : Re: [zauguin/luapstricks] Problem between pstricks, xcolor, luatex and pdfmanagement (Issue #88)

 

Do not load xcolor, it is already be done by PSTricks itself.

**Comment by hvoss49** [comment]
I see. I have to investigate tomorrow.

**Comment by hvoss49** [comment]
Ok, found the problem ... Will upload a new version to CTAN.

**Comment by fpantigny** [comment]
Thanks.

 

De : Herbert Voß ***@***.***> 
Envoyé : lundi 6 novembre 2023 21:28
À : zauguin/luapstricks ***@***.***>
Cc : fpantigny ***@***.***>; Author ***@***.***>
Objet : Re: [zauguin/luapstricks] Problem between pstricks, xcolor, luatex and pdfmanagement (Issue #88)

 

Ok, found the problem ... Will upload a new version to CTAN.

**Comment by pablgonz** [comment]
@hvoss49 @fpantigny Can you close this?
