### ISSUE TITLE
removing  the special `pstricks.con`

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#9]
I like to put the Lua specific code into `pstricks.tex` itself. Here is a patch for the
up-to-date version of PSTricks (from today). Then we do not need a special `pstricks.con`

```
@@ -428,22 +429,46 @@
     \fi%
 }
 \fi
-%-------------- end old vesrion ---------------
+%-------------- end old version ---------------
 %
 \def\pst@configerr#1{\@pstrickserr{\string#1 not defined in pstricks.con}\@ehpc}
+\newif\ifPSTricks
 %
-\def\pstVerb#1{\pst@configerr\pstVerb}
-\def\pstverb#1{\pst@configerr\pstverb}
-\def\pstverbscale{\pst@configerr\pstverbscale}
-\def\pstrotate{\pst@configerr\pstrotate}
-\def\pstheader#1{\pst@configerr\pstheader}
-\def\pstdriver{\pst@configerr\pstdriver}
-\@ifundefined{pstcustomize}%
-  {\def\pstcustomize{\endinput\let\pstcustomize\relax}}{}
-%
-\input pstricks.con		% local config file
+\ifdefined\directlua
+  \ifdefined\app@cmd@latex % do we have auto-pst-pdf-lua loaded?
+    \PSTrickstrue  % 
+    \typeout{--- We are running lualatex with auto-pst-pdf-lua ---}%
+  \else  
+    \PSTricksfalse  % 
+    \typeout{--- We are running lualatex with luapstricks ---}%
+  \fi
+\else
+  \typeout{--- We are running latex or xelatex ---}%
+  \PSTrickstrue    
+\fi
+\ifPSTricks
+  \def\pstVerb#1{\pst@configerr\pstVerb}%
+  \def\pstverb#1{\pst@configerr\pstverb}%
+  \def\pstverbscale{\pst@configerr\pstverbscale}%
+  \def\pstrotate{\pst@configerr\pstrotate}%
+  \def\pstheader#1{\pst@configerr\pstheader}%
+  \def\pstdriver{\pst@configerr\pstdriver}%
+  \@ifundefined{pstcustomize}%
+    {\def\pstcustomize{\endinput\let\pstcustomize\relax}}{}%
+  \input pstricks.con		% local config file
+\else
+  \directlua{require'luapstricks'}%
+  \def\pstdriver{LuaLaTeX}%
+  \def\pstverb{\luaPST}%
+  \def\pstVerb{\luaPST direct}%
+  \def\pstunit{1bp}%
+  \def\pstverbscale{}%
+  \def\pstnodescale{}%
+  \def\pstheader{\luaPSTheader}%
+  % Not sure if we need ``neg'' here or not
+  % \def\pstrotate{CP CP translate 3 -1 roll neg rotate \tx@NET}
+\fi
 %
-\newif\ifPSTricks
 \PSTrickstrue
 \def\PSTricksOff{%
   \def\pstheader##1{}%
```

I tried it with the grid font example for all variants: 
- latex->drips->ps2pdf
- pdflatex with auto-pst-pdf
- xelatex
- lualatex with auto-pst-pdf-lua
- lualatex with luapstricks

**Comment by zauguin** [comment]
> +\ifdefined\directlua

I think this should additionally test if `\outputmode` is 1, so if PDF is generated. The code is pretty PDF specific and in `dvilualatex` "regular" pstricks should be more appropriate anyway (Not sure how that interacts with `auto-pst-pdf-lua` though since that uses `dvilualatex` too).

Additionally it might make sense to add

    \def\c@lor@to@ps#1\@@{(#1) setpdfcolor}

there too, then `luapstricks.sty` is no longer needed either.

**Comment by hvoss49** [comment]
Yes, forgot about `dvilualatex`. I added the color definition into `pstricks.tex`. The `luapstricks` is now obsolet. Will do some more test and upload it tomorrow to CTAN.

**Comment by zauguin** [comment]
Thanks. I removed the no longer needed files and updated the README.

**Comment by hvoss49** [comment]
`pstricks.tex` is uploaded to CTAN and should be available tomorrow from all mirrors. The complete package is also here: https://hvoss.org/pstricks-base.zip
