### ISSUE TITLE
Problem with `epic`+`eepic`

### ISSUE THREAD

**Issue by dbitouze** [zauguin/luapstricks#90]
The following MCE:
```latex
\documentclass{article}
\usepackage{epic,eepic}
\begin{document}
\circle{100}
\end{document}
```
does display the circle with `latex` + `dvips` + `ps2pdf` and with `xelatex`, but not with `lualatex`.

**Comment by hvoss49** [comment]
Sure, it needs the dvi route ... 

```latex
\documentclass{article}
\usepackage{epic,eepic}
\usepackage{auto-pst-pdf-lua}
\begin{document}
	
\begin{postscript}
\circle{100}
\end{postscript}

\end{document}
```

**Comment by zauguin** [comment]
I'm not an expert regarding to `epic` / `eepic`, so: What is the relation of `epic` / `eepic` to `pstricks`? How does this relate to `luapstricks`?

**Comment by hvoss49** [comment]
There is no relation.

**Comment by dbitouze** [comment]
> There is no relation.

Oooops! Sorry for the noise.

**Comment by zauguin** [comment]
@dbitouze Do you have a usecase for having `epic` / `eepic` support in LuaLaTeX? It shouldn't be hard to support in a separate package if needed.

**Comment by hvoss49** [comment]
There is also a package `pict2e`  which does the same but works with all engines ...

**Comment by dbitouze** [comment]
@zauguin In fact not, sorry. I reported just because I encountered this limitation while I was working on [this question](https://faq.gutenberg-asso.fr/3_composition/illustrations/construire_un_arbre.html) of the [GUTenberg (French) LaTeX FAQ](https://faq.gutenberg-asso.fr/index.html): when possible, I try to replace `xelatex` by `lualatex`.

**Comment by dbitouze** [comment]
@zauguin In fact not, sorry. I reported just because I encountered this limitation while I was working on [this question](https://faq.gutenberg-asso.fr/3_composition/illustrations/construire_un_arbre.html) of the [GUTenberg (French) LaTeX FAQ](https://faq.gutenberg-asso.fr/index.html): when possible, I try to replace `xelatex` by `lualatex`.
